[graph]
targets = [
    # Flathub builds these targets
    { triple = 'x86_64-unknown-linux-gnu' },
    { triple = 'aarch64-unknown-linux-gnu' },
]

[advisories]
version = 2
ignore = []

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
]
