
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.gnome-releng]
url = "https://gitlab.gnome.org/Teams/Releng/rust-supply-chain/-/raw/main/gnome-audited/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.swsnr]
url = "https://raw.githubusercontent.com/swsnr/rust-supply-chain/refs/heads/main/audits.toml"

[policy.umbrella]
criteria = "safe-to-run"

[[exemptions.autocfg]]
version = "1.4.0"
criteria = "safe-to-run"

[[exemptions.bitflags]]
version = "2.8.0"
criteria = "safe-to-run"

[[exemptions.cairo-rs]]
version = "0.20.7"
criteria = "safe-to-run"

[[exemptions.cairo-sys-rs]]
version = "0.20.7"
criteria = "safe-to-run"

[[exemptions.gdk-pixbuf]]
version = "0.20.7"
criteria = "safe-to-run"

[[exemptions.gdk-pixbuf-sys]]
version = "0.20.7"
criteria = "safe-to-run"

[[exemptions.gdk4]]
version = "0.9.5"
criteria = "safe-to-run"

[[exemptions.gdk4-sys]]
version = "0.9.5"
criteria = "safe-to-run"

[[exemptions.gio]]
version = "0.20.7"
criteria = "safe-to-run"

[[exemptions.gio-sys]]
version = "0.20.8"
criteria = "safe-to-run"

[[exemptions.glib]]
version = "0.20.7"
criteria = "safe-to-run"

[[exemptions.glib-macros]]
version = "0.20.7"
criteria = "safe-to-run"

[[exemptions.glib-sys]]
version = "0.20.7"
criteria = "safe-to-run"

[[exemptions.gobject-sys]]
version = "0.20.7"
criteria = "safe-to-run"

[[exemptions.graphene-rs]]
version = "0.20.7"
criteria = "safe-to-run"

[[exemptions.graphene-sys]]
version = "0.20.7"
criteria = "safe-to-run"

[[exemptions.gsk4]]
version = "0.9.5"
criteria = "safe-to-run"

[[exemptions.gsk4-sys]]
version = "0.9.5"
criteria = "safe-to-run"

[[exemptions.gtk4]]
version = "0.9.5"
criteria = "safe-to-run"

[[exemptions.gtk4-macros]]
version = "0.9.5"
criteria = "safe-to-run"

[[exemptions.gtk4-sys]]
version = "0.9.5"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.15.2"
criteria = "safe-to-run"

[[exemptions.indexmap]]
version = "2.7.0"
criteria = "safe-to-run"

[[exemptions.libadwaita]]
version = "0.7.1"
criteria = "safe-to-run"

[[exemptions.libadwaita-sys]]
version = "0.7.1"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.169"
criteria = "safe-to-run"

[[exemptions.memchr]]
version = "2.7.4"
criteria = "safe-to-run"

[[exemptions.pango]]
version = "0.20.7"
criteria = "safe-to-run"

[[exemptions.pango-sys]]
version = "0.20.7"
criteria = "safe-to-run"

[[exemptions.pin-project-lite]]
version = "0.2.16"
criteria = "safe-to-run"

[[exemptions.proc-macro-crate]]
version = "3.2.0"
criteria = "safe-to-run"

[[exemptions.proc-macro2]]
version = "1.0.93"
criteria = "safe-to-run"

[[exemptions.serde_spanned]]
version = "0.6.8"
criteria = "safe-to-run"

[[exemptions.slab]]
version = "0.4.9"
criteria = "safe-to-run"

[[exemptions.smallvec]]
version = "1.13.2"
criteria = "safe-to-run"

[[exemptions.syn]]
version = "2.0.96"
criteria = "safe-to-run"

[[exemptions.target-lexicon]]
version = "0.12.16"
criteria = "safe-to-run"

[[exemptions.toml_edit]]
version = "0.22.22"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.winnow]]
version = "0.6.24"
criteria = "safe-to-run"
