name: gettext

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - src/**/*.rs
      - resources/**/*.blp
      - resources/de.swsnr.umbrella.metainfo.xml.in
      - de.swsnr.umbrella.desktop.in
      - Makefile
      - .github/workflows/gettext.yml

jobs:
  xgettext:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    container:
      image: docker.io/fedora:latest
    steps:
      # We need appstream as it provides extraction rules for metainfo files
      - name: Install git, make, gettext, and appstream
        run: dnf install -y git make gettext appstream
      - uses: actions/checkout@v4
      - run: make pot
      # Create a pull request to update the messages file
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: |
            Update messages

            Github bot runs make pot :v:
          branch: workflow/update-messages
          base: main
          sign-commits: true
          delete-branch: true
          title: "Update messages"
          body: "Github bot runs make pot :v:"
          assignees: swsnr
          draft: true
          add-paths: po/de.swsnr.umbrella.pot
